DROP TABLE IF EXISTS contest_leaderboard;
DROP TABLE IF EXISTS info;
DROP TABLE IF EXISTS activity;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS contests;
DROP TABLE IF EXISTS problems;
DROP TABLE IF EXISTS users;
